"""
This file is used as routes for the users app API's.
"""

from django.conf.urls import url, re_path
from .views import (
    InviteUserView,
    UpdateUserView,
    GetCityListView,
    ClearAllAPIView,
    FCMDeviceViewSet,
    UpdateUserViewOld,
    UserLoginAPIView,
    ListAdminUsersView,
    GetAdminUsersRolesView,
    SaveAdminUserRolesView,
    SuperUserSignUpAPIView,
    AdminUserDeleteAPIView,
    UpgradeOrDowngradeAPIView,
    SearchUserAPIView,
    UserSignUpAPIView,
    UserLogoutAPIView,
    UserTokenUpdateView,
    GetUserDetailAPIView,
    SendContactUsAPIView,
    PasswordResetRequest,
    UpdateUserStatusView,
    ChangePasswordAPIView,
    DeleteFCMDeviceViewSet,
    GetNotificationListView,
    ForgotPasswordRequestView,
    GetApplicationDetailAPIView,
    UpdateNotificationStatusView,
    UserForgotPasswordRequestView,
    ValidateEmailVerificationView,
    GenerateEmailVerificationView,
    GeneratePhoneVerificationView,
    ValidatePhoneVerificationView,
    VendorForgotPasswordRequestView,
    GetStateListView,
    AddVendorAPIView,
    GetUserDetailView,
    UserAuthView,
    VerifyUserView,
    CreateUserProfileView,
    AddCityView,
    AppleSinInView,
    DeleteUsersOnNumberOrEmail,
    UpdateUserViewOld,
    GetUserDetailAPIViewOld,
    UpdateUserStatusViewOld,
    GeneratePhoneVerificationViewOld,
    AddVendorAPIViewOld,
    VenuesByCityAPIView,
    ImageUploadView,
    UserListAPI,
    CityUpdateAPIView,
    AllPromotionalMessageView,
    RetrievePromotionalMessageView,
    CreatePromotionalMessageView,
    DestroyPromotionalMessageView,
    UpdatePromotionalMessageView,
    GetDownloadCount,
)

urlpatterns = [
    url("v1/usersList", UserListAPI.as_view(), name="usersList"),
    url("v1/uploadImageToS3", ImageUploadView.as_view(), name="upload-image-to-s3"),
    url("v1/venuesByCity", VenuesByCityAPIView.as_view(), name="venues-by-city"),
    url("v1/appleSignIn", AppleSinInView.as_view(), name="apple-sign-in"),
    url("v1/addCity", AddCityView.as_view(), name="add-city"),
    url("v1/updateCity/(?P<pk>.+)", CityUpdateAPIView.as_view(), name="updateCity"),
    url("v1/auth", UserAuthView.as_view(), name="user-auth"),
    url("v1/verifyUser", VerifyUserView.as_view(), name="verify-user"),
    url(
        "v1/createProfile", CreateUserProfileView.as_view(), name="create-user-profile"
    ),
    url("signup", UserSignUpAPIView.as_view(), name="user-register"),
    url("login", UserLoginAPIView.as_view(), name="login"),
    url("listAdminUsers", ListAdminUsersView.as_view(), name="list-admin-users"),
    url("getUserRoles", GetAdminUsersRolesView.as_view(), name="get-user-roles"),
    url("saveUserRoles", SaveAdminUserRolesView.as_view(), name="save-user-roles"),
    url("createSuperUser", SuperUserSignUpAPIView.as_view(), name="create-super-user"),
    url("deleteSuperUser", AdminUserDeleteAPIView.as_view(), name="delete-super-user"),
    url(
        "upgradeOrDowngradeUser",
        UpgradeOrDowngradeAPIView.as_view(),
        name="upgrade-user-to-admin",
    ),
    url("searchUser", SearchUserAPIView.as_view(), name="search-user"),
    url("v1/logout", UserLogoutAPIView.as_view(), name="logout"),
    url("logout", UserLogoutAPIView.as_view(), name="logout"),
    url("v1/generateToken", UserTokenUpdateView.as_view(), name="token-update"),
    url("generateToken", UserTokenUpdateView.as_view(), name="token-update"),
    url(
        "v1/forgotPasswordRequest",
        ForgotPasswordRequestView.as_view(),
        name="email-request",
    ),
    url(
        "forgotPasswordRequest",
        ForgotPasswordRequestView.as_view(),
        name="email-request",
    ),
    url(
        "v1/userForgotPasswordRequest",
        UserForgotPasswordRequestView.as_view(),
        name="user-forgot-password",
    ),
    url(
        "userForgotPasswordRequest",
        UserForgotPasswordRequestView.as_view(),
        name="user-forgot-password",
    ),
    url(
        "v1/vendorForgotPasswordRequest",
        VendorForgotPasswordRequestView.as_view(),
        name="vendor-forgot-password",
    ),
    url(
        "vendorForgotPasswordRequest",
        VendorForgotPasswordRequestView.as_view(),
        name="vendor-forgot-password",
    ),
    url(
        "v1/confirmPasswordRequest",
        PasswordResetRequest.as_view(),
        name="confirm-password",
    ),
    url(
        "confirmPasswordRequest",
        PasswordResetRequest.as_view(),
        name="confirm-password",
    ),
    url("v1/changePassword/", ChangePasswordAPIView.as_view(), name="changePassword"),
    url("changePassword/", ChangePasswordAPIView.as_view(), name="changePassword"),
    url("v1/inviteUser/", InviteUserView.as_view(), name="user-invite"),
    url("inviteUser/", InviteUserView.as_view(), name="user-invite"),
    url(
        "v1/updateUser/(?P<pk>.+)", UpdateUserView.as_view(), name="update-user-profile"
    ),
    url(
        "updateUser/(?P<pk>.+)", UpdateUserViewOld.as_view(), name="update-user-profile"
    ),
    url(
        "v1/updateUserStatus/(?P<pk>.+)",
        UpdateUserStatusView.as_view(),
        name="update-user-status",
    ),
    url(
        "updateUserStatus/(?P<pk>.+)",
        UpdateUserStatusViewOld.as_view(),
        name="update-user-status",
    ),
    url(
        "v1/emailVerification",
        GenerateEmailVerificationView.as_view(),
        name="email-verification",
    ),
    url(
        "emailVerification",
        GenerateEmailVerificationView.as_view(),
        name="email-verification",
    ),
    url("v1/verifyEmail", ValidateEmailVerificationView.as_view(), name="verify-email"),
    url("verifyEmail", ValidateEmailVerificationView.as_view(), name="verify-email"),
    url(
        "v1/phoneVerification",
        GeneratePhoneVerificationView.as_view(),
        name="phone-verification",
    ),
    url(
        "phoneVerification",
        GeneratePhoneVerificationViewOld.as_view(),
        name="phone-verification",
    ),
    url("v1/verifyPhone", ValidatePhoneVerificationView.as_view(), name="verify-phone"),
    url("verifyPhone", ValidatePhoneVerificationView.as_view(), name="verify-phone"),
    url("v1/getStateList", GetStateListView.as_view(), name="get-state"),
    url("getStateList", GetStateListView.as_view(), name="get-state"),
    url("v1/getCityList", GetCityListView.as_view(), name="get-cities"),
    url("getCityList", GetCityListView.as_view(), name="get-cities"),
    url(
        "v1/getNotifications",
        GetNotificationListView.as_view(),
        name="get-notification",
    ),
    url("getNotifications", GetNotificationListView.as_view(), name="get-notification"),
    url(
        "v1/updateNotificationStatus/(?P<pk>.+)",
        UpdateNotificationStatusView.as_view(),
        name="update-notification",
    ),
    url(
        "updateNotificationStatus/(?P<pk>.+)",
        UpdateNotificationStatusView.as_view(),
        name="update-notification",
    ),
    url("v1/contactUs", SendContactUsAPIView.as_view(), name="contact-us"),
    url("contactUs", SendContactUsAPIView.as_view(), name="contact-us"),
    url(
        "v1/getApplicationDetail",
        GetApplicationDetailAPIView.as_view(),
        name="get-application-cred",
    ),
    url(
        "getApplicationDetail",
        GetApplicationDetailAPIView.as_view(),
        name="get-application-cred",
    ),
    url("v1/getUserDetails", GetUserDetailAPIView.as_view(), name="get-user_details"),
    url("getUserDetails", GetUserDetailAPIViewOld.as_view(), name="get-user_details"),
    url("v1/fcmRegister", FCMDeviceViewSet.as_view(), name="create_fcm_device"),
    url("fcmRegister", FCMDeviceViewSet.as_view(), name="create_fcm_device"),
    url("v1/fcmUnRegister", DeleteFCMDeviceViewSet.as_view(), name="delete_fcm_device"),
    url("fcmUnRegister", DeleteFCMDeviceViewSet.as_view(), name="delete_fcm_device"),
    url("v1/clearAll", ClearAllAPIView.as_view(), name="clear-all"),
    url("clearAll", ClearAllAPIView.as_view(), name="clear-all"),
    url("v1/addVendorAPI", AddVendorAPIView.as_view(), name="add_vendor"),
    url("addVendorAPI", AddVendorAPIViewOld.as_view(), name="add_vendor"),
    url("v1/get_user_detail", GetUserDetailView.as_view(), name="get_user_detail"),
    url("get_user_detail", GetUserDetailView.as_view(), name="get_user_detail"),
    url("v1/deleteUsers", DeleteUsersOnNumberOrEmail.as_view(), name="delete_users"),
    url(
        "v1/getAllPromotionalMesage",
        AllPromotionalMessageView.as_view(),
        name="get-all-promotional-message",
    ),
    url(
        "v1/getPromotionalMessage/(?P<id>.+)",
        RetrievePromotionalMessageView.as_view(),
        name="retrieve-promotional-message",
    ),
    url(
        "v1/createPromotionalMessage",
        CreatePromotionalMessageView.as_view(),
        name="create-promotional-message",
    ),
    url(
        "v1/removePromotionalMessage/(?P<id>.+)",
        DestroyPromotionalMessageView.as_view(),
        name="delete-promotional-message",
    ),
    url(
        "v1/updatePromotionalMessage/(?P<id>.+)",
        UpdatePromotionalMessageView.as_view(),
        name="update-promotional-message",
    ),
      url("getDownloads/", 
        GetDownloadCount.as_view(),
        name="get_downloads_count"
    ),
]
